# Generated by Django 5.1.5 on 2025-02-02 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('virustotal', 'VirusTotal'), ('crowdsec', 'CrowdSec'), ('greynoise', 'GreyNoise'), ('abuseipdb', 'AbuseIPDB'), ('hybrid_analysis', 'Hybrid Analysis'), ('alienvault', 'AlienVault OTX'), ('pulsedive', 'Pulsedive'), ('filescan', 'FileScan.io'), ('urlscan', 'URLScan.io'), ('securitytrails', 'SecurityTrails'), ('phishtank', 'PhishTank'), ('malwarebazaar', 'MalwareBazaar'), ('threatfox', 'ThreatFox'), ('urlhaus', 'URLhaus'), ('cisco_talos', 'Cisco Talos'), ('threatminer', 'ThreatMiner'), ('spamhaus', 'SpamHaus'), ('cleantalk', 'CleanTalk'), ('phishstats', 'PhishStats')], max_length=50)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
