# Generated by Django 5.1.5 on 2025-02-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='platform',
            field=models.CharField(choices=[('virustotal', 'VirusTotal'), ('crowdsec', 'CrowdSec'), ('greynoise', 'GreyNoise'), ('abuseipdb', 'AbuseIPDB'), ('hybrid_analysis', 'Hybrid Analysis'), ('alienvault', 'AlienVault OTX'), ('pulsedive', 'Pulsedive'), ('filescan', 'FileScan.io'), ('urlscan', 'URLScan.io'), ('securitytrails', 'SecurityTrails'), ('malwarebazaar', 'MalwareBazaar'), ('threatfox', 'ThreatFox'), ('urlhaus', 'URLhaus'), ('cisco_talos', 'Cisco Talos'), ('threatminer', 'ThreatMiner'), ('spamhaus', 'SpamHaus'), ('cleantalk', 'CleanTalk'), ('phishstats', 'PhishStats')], max_length=50),
        ),
    ]
